(function($){var cntrlIsPressed=!1;$(document).keydown(function(e){if(e.metaKey||e.ctrlKey){cntrlIsPressed=!0}});$(document).on('click','.a-container',function(e){e.preventDefault();var target='_self';if(cntrlIsPressed){e.preventDefault();target='_blank'}
window.open($(this).find('a').attr('href'),target)
return});$(document).on('mouseup','.a-container',function(e){if(e.which===2){if(e.target.localName=="a"||e.target.localName=="h3"){return!1}
window.open($(this).find('a').attr('href'));return!1}});$(function(){if($('form.wpcf7-form').length){$('.form-row > label').each(function(){var forval=$(this).attr('for');var input=$(this).parent().find('span').find('input, textarea');input.attr('placeholder',' ');if(input.attr('aria-required')=='true'){input.prop('required',!0)}
if(input.attr('id')==forval){$(this).insertAfter(input)}})}});$('a[data-hw-cc-btn-toggle-modal=""]').on('click',function(event){event.preventDefault()});function encryptedRedirect(elem){var url=rot13(elem.data('href'));var hostname=$('<a>').prop('href',url).prop('hostname');var target='_blank';if(window.location.href.indexOf(hostname)>-1){if(url.indexOf(hostname+'/tools/redirection/')===-1){var target='_self'}}
window.open(url,target);return}
function rot13(s){return(s?s:this).split('').map(function(_){if(!_.match(/[A-Za-z]/))return _;c=Math.floor(_.charCodeAt(0)/97);k=(_.toLowerCase().charCodeAt(0)-83)%26||26;return String.fromCharCode(k+((c==0)?64:96))}).join('')}
$(document).on('click','.e-link',function(e){e.preventDefault();encryptedRedirect($(this))});$(document).on('keypress','.e-link',function(e){if(e.which==13){encryptedRedirect($(this))}});$('.e-link').attr('tabindex','0');$(".entry-content a:not([href$='.jpg']):not([href$='.jpeg']):not([href$='.gif']):not([href$='.png'])").each(function(){var a=new RegExp('/'+window.location.host+'/');if(!a.test(this.href)){var e_rel=$(this).attr('rel');if(e_rel==null){e_rel='noopener'}else if(e_rel.indexOf('noopener')===-1){e_rel=e_rel+' noopener'}
$(this).addClass('external').attr('target','_blank').attr('rel',e_rel)}});var hashTagActive="";$('a').bind('click.smoothscroll',function(event){if(hashTagActive!=$(this.hash)&&$(this.hash).length){event.preventDefault();$link_url=$(this).attr("href");$link_url=$link_url.substr(0,$link_url.indexOf('#'));$page_url=window.location.href;if($page_url.substr(0,$page_url.indexOf('#')).length){$page_url=$page_url.substr(0,$page_url.indexOf('#'))};if($link_url!==$page_url&&$page_url.length&&$link_url.length){$(location).attr('href',$(this).attr("href"))}else{var theHash=$(this.hash);var dest=0;var navbarTop=$('#main-menu').height()+20;setTimeout(function(){if(theHash.offset().top>$(document).height()-$(window).height()){dest=$(document).height()-$(window).height()-navbarTop}else{dest=theHash.offset().top-navbarTop}
hashTagActive=theHash;$('html,body').animate({'scrollTop':dest},500)},100)}}});$(function(){if(window.location.hash&&$(window.location.hash).length){var dest=0;var navbarTop=$('#main-menu').height()+20;if($(window.location.hash).offset().top>$(document).height()-$(window).height()){dest=$(document).height()-$(window).height()-navbarTop}else{dest=$(window.location.hash).offset().top-navbarTop}
hashTagActive=window.location.hash;$('html,body').animate({scrollTop:dest},500,function(){document.location.hash=hashTagActive})}});$(function(){if($('.landing-form').length){var form_col=$('.landing-form-container');var offset_title=$('.landing-banner h1').offset().top;window.addEventListener('load',function(){setTimeout(function(){var margin=0;if($('.landing-form').height()*1.25<$('body.landing-form-tpl .entry-content').height()&&$('.landing-form').height()*1.20<$(window).height()){$('.landing-form').addClass('sticky-form')}
if($(window).width()>992){var offset_form=form_col.offset().top;margin=offset_form-offset_title-18}
form_col.animate({'margin-top':'-'+margin,'opacity':1},{duration:200,easing:'swing'})},200)});var res_throttle=!0;$(window).on('resize',function(){if(res_throttle){res_throttle=!1;setTimeout(function(){if($(window).width()>992){var offset_form=form_col.offset().top;var margin=offset_form-offset_title-parseInt(form_col.css('margin-top'));margin=0-margin-18;form_col.animate({'margin-top':margin},{duration:200,easing:'swing'})}else{form_col.css({'margin-top':0})}
res_throttle=!0},200)}})}})})(jQuery);function bdmModalDisplay(show=!0,elem=!1){if(!elem){elem=jQuery('.modal')}
if(show){elem.fadeIn(300).addClass('show');if(jQuery(window).width()<769){jQuery('body').css('overflow','hidden')}}else{elem.fadeOut(300).removeClass('show');jQuery('body').css('overflow','')}}
jQuery('.modal, .modal .close, .modal .close *').on('click',function(e){if(e.target!=this)return;e.preventDefault();bdmModalDisplay(!1)});jQuery(document).keyup(function(e){if(e.keyCode===27&&jQuery('.modal').hasClass('show')){jQuery('.modal').fadeOut(300).removeClass('show');bdmModalDisplay(!1)}})