function load_observer_list(){var lists=document.querySelectorAll(".list-visibility:not(.listen)");for(let ilist=0;ilist<lists.length;ilist++){isInViewPort.observe(document.querySelector("#"+lists[ilist].id));lists[ilist].classList.add("listen")}}
var isInViewPort=new IntersectionObserver(function(entries){if(entries[0].isIntersecting===!0){bdm_event(window[entries[0].target.id]);isInViewPort.unobserve(entries[0].target)}
return!0},{threshold:[0]});document.addEventListener("DOMContentLoaded",function(e){load_observer_list()});function bdm_event(data){var Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",decode:function(input){var output="";var chr1,chr2,chr3;var enc1,enc2,enc3,enc4;var i=0;input=input.replace(/[^A-Za-z0-9\+\/\=]/g,"");while(i<input.length){enc1=this._keyStr.indexOf(input.charAt(i++));enc2=this._keyStr.indexOf(input.charAt(i++));enc3=this._keyStr.indexOf(input.charAt(i++));enc4=this._keyStr.indexOf(input.charAt(i++));chr1=(enc1<<2)|(enc2>>4);chr2=((enc2&15)<<4)|(enc3>>2);chr3=((enc3&3)<<6)|enc4;output=output+String.fromCharCode(chr1);if(enc3!=64){output=output+String.fromCharCode(chr2)}
if(enc4!=64){output=output+String.fromCharCode(chr3)}}
output=Base64._utf8_decode(output);return output},_utf8_decode:function(utftext){var string="";var i=0;var c=c1=c2=0;while(i<utftext.length){c=utftext.charCodeAt(i);if(c<128){string+=String.fromCharCode(c);i++}else if((c>191)&&(c<224)){c2=utftext.charCodeAt(i+1);string+=String.fromCharCode(((c&31)<<6)|(c2&63));i+=2}else{c2=utftext.charCodeAt(i+1);c3=utftext.charCodeAt(i+2);string+=String.fromCharCode(((c&15)<<12)|((c2&63)<<6)|(c3&63));i+=3}}
return string}}
data=data.substring(0,data.length-2);data=Base64.decode((data));dataLayer.push({ecommerce:null});dataLayer.push(JSON.parse(data))}
GA_events_posts=function(container,events_all=!0){if(jQuery(container.find('.cats-list span')).length>0){jQuery(container.find('.cats-list span')).each(function(){if(jQuery(this).is(":visible")&&jQuery(this).data('cat')){dataLayer.push({'event':'EventGeneric','EventCat':'Load','EventAction':'Categorie','EventLibelle':jQuery(this).data('cat')})}})}
if(jQuery(container.find('.tags-list a')).length>0){jQuery(container.find('.tags-list a')).each(function(){if(jQuery(this).is(":visible")&&jQuery(this).data('tag')){dataLayer.push({'event':'EventGeneric','EventCat':'Load','EventAction':'Tag','EventLibelle':jQuery(this).data('tag')})}})}
if(events_all){container.find('a.featured-link:not(.no-event)').on('click',function(){dataLayer.push({'event':'EventGeneric','EventCat':'Actualite','EventAction':'Redirection','EventLibelle':'Lien - '+jQuery(this).attr('href')})})}
if(jQuery(container.find('.card-emploi a')).length>0){jQuery(container.find('.card-emploi a')).each(function(){if(jQuery(this).is(":visible")){dataLayer.push({'event':'EventGeneric','EventCat':'Encart','EventAction':'Load','EventLibelle':'HelloWork - '+jQuery(this).data("event")+' - '+jQuery(this).data("url")})}})}
if(events_all){container.find('.card-emploi a').on('click',function(){dataLayer.push({'event':'EventGeneric','EventCat':'Encart','EventAction':'Redirection','EventLibelle':'HelloWork - '+jQuery(this).data("event")+' - '+jQuery(this).data("url")})})}
if(jQuery(container.find('.card-formation a')).length>0){jQuery(container.find('.card-formation a')).each(function(){if(jQuery(this).is(":visible")){dataLayer.push({'event':'EventGeneric','EventCat':'Encart','EventAction':'Load','EventLibelle':'MaFormation - '+jQuery(this).data("event")+' - '+jQuery(this).data("url")})}})}
if(events_all){container.find('.card-formation a').on('click',function(){dataLayer.push({'event':'EventGeneric','EventCat':'Encart','EventAction':'Redirection','EventLibelle':'MaFormation - '+jQuery(this).data("event")+' - '+jQuery(this).data("url")})})}
if(jQuery(container.find('.entry-content .tools-list .tools-item a')).length>0){jQuery(container.find('.entry-content .tools-list .tools-item a')).each(function(){if(jQuery(this).is(":visible")){dataLayer.push({'event':'EventGeneric','EventCat':'Encart','EventAction':'Load','EventLibelle':'Tools - Liste article - '+jQuery(this).data('name')})}})}
if(events_all){container.find('.entry-content .tools-list .tools-item a').on('click',function(){dataLayer.push({'event':'EventGeneric','EventCat':'Encart','EventAction':'Redirection','EventLibelle':'Tools - Liste article - '+jQuery(this).data('name')})})}
if(jQuery(container.find('.entry-content .tool-single .tools-item a')).length>0){jQuery(container.find('.entry-content .tool-single .tools-item a')).each(function(){if(jQuery(this).is(":visible")){dataLayer.push({'event':'EventGeneric','EventCat':'Encart','EventAction':'Load','EventLibelle':'Tools - Encart article - '+jQuery(this).data('name')})}})}
if(events_all){container.find('.entry-content .tool-single .tools-item a').on('click',function(){dataLayer.push({'event':'EventGeneric','EventCat':'Encart','EventAction':'Redirection','EventLibelle':'Tools - Encart article - '+jQuery(this).data('name')})})}
if(jQuery(container.find('.tools-container .item > div')).length>0){jQuery(container.find('.tools-container .item > div')).each(function(){if(jQuery(this).is(":visible")){dataLayer.push({'event':'EventGeneric','EventCat':'Encart','EventAction':'Load','EventLibelle':'Tools - Footer article - '+jQuery(this).data('name')})}})}
if(events_all){container.find('.tools-container .item > div').on('click',function(){dataLayer.push({'event':'EventGeneric','EventCat':'Encart','EventAction':'Redirection','EventLibelle':'Tools - Footer article - '+jQuery(this).data('name')})})}
if(jQuery(container.find('.skills-container .item > div')).length>0){jQuery(container.find('.skills-container .item > div')).each(function(){if(jQuery(this).is(":visible")){dataLayer.push({'event':'EventGeneric','EventCat':'Encart','EventAction':'Load','EventLibelle':'Skills - Footer article - '+jQuery(this).data('name')})}})}
if(events_all){container.find('.skills-container .item > div').on('click',function(){dataLayer.push({'event':'EventGeneric','EventCat':'Encart','EventAction':'Redirection','EventLibelle':'Skills - Footer article - '+jQuery(this).data('name')})})}
if(jQuery(container.find('a.skills-link')).length>0){jQuery(container.find('a.skills-link')).each(function(){if(jQuery(this).is(":visible")){dataLayer.push({'event':'EventGeneric','EventCat':'Actualite','EventAction':'Load','EventLibelle':'Skills - Selection article - '+jQuery(this).data('name')})}})}
if(events_all){container.find('a.skills-link').on('click',function(){dataLayer.push({'event':'EventGeneric','EventCat':'Actualite','EventAction':'Redirection','EventLibelle':'Skills - Selection article - '+jQuery(this).data('name')})})}
if(jQuery(container.find('span.skills-list-link')).length>0){jQuery(container.find('span.skills-list-link')).each(function(){if(jQuery(this).is(":visible")){dataLayer.push({'event':'EventGeneric','EventCat':'Encart','EventAction':'Load','EventLibelle':'Skills - Liste article - '+jQuery(this).data('name')})}})}
if(events_all){container.find('span.skills-list-link').on('click',function(){dataLayer.push({'event':'EventGeneric','EventCat':'Encart','EventAction':'Redirection','EventLibelle':'Skills - Liste article - '+jQuery(this).data('name')})})}};window.addEventListener("DOMContentLoaded",(event)=>{(function($){GA_events_posts(jQuery('#main > .post-content'));var container=$('body.home #primary');if(jQuery(container.find('.tools-container .items-list a')).length>0){jQuery(container.find('.tools-container .items-list a')).each(function(){if(jQuery(this).is(":visible")){dataLayer.push({'event':'EventGeneric','EventCat':'Encart','EventAction':'Load','EventLibelle':'Tools - Homepage - '+jQuery(this).data('name')})}})}
container.find('.tools-container .items-list a').on('click',function(){dataLayer.push({'event':'EventGeneric','EventCat':'Encart','EventAction':'Redirection','EventLibelle':'Tools - Homepage - '+jQuery(this).data('name')})});if(jQuery(container.find('.skills-container .item > div')).length>0){jQuery(container.find('.skills-container .item > div')).each(function(){if(jQuery(this).is(":visible")){dataLayer.push({'event':'EventGeneric','EventCat':'Encart','EventAction':'Load','EventLibelle':'Skills - Homepage - '+jQuery(this).data('name')})}})}
container.find('.skills-container .item > div').on('click',function(){dataLayer.push({'event':'EventGeneric','EventCat':'Encart','EventAction':'Redirection','EventLibelle':'Skills - Homepage - '+jQuery(this).data('name')})});var container=$('body.page-template-skills-template #primary');if(jQuery(container.find('.formations .more')).length>0){jQuery(container.find('.formations .more')).each(function(){if(jQuery(this).is(":visible")){dataLayer.push({'event':'EventGeneric','EventCat':'Encart','EventAction':'Load','EventLibelle':'Skills - SERP - '+jQuery(this).data('name')})}})}
container.find('.formations .btn, .formations .more').on('click',function(){dataLayer.push({'event':'EventGeneric','EventCat':'Encart','EventAction':'Redirection','EventLibelle':'Skills - SERP - '+jQuery(this).data('name')})})})(jQuery)});(function($){$(document).ready(function(){var tracked_area=[{container:'.last-posts-container .posts-list',item:'.a-container',cta:'a.cta',event:'Article'},{container:'.tools-container .items-list',item:'.item > a',cta:'',event:'Tools'},{container:'.events-container',item:'.item > div',cta:'a.cta',event:'Événement'},{container:'.stickies-container .items-list',item:'.item > a',cta:'',event:'À la une'},{container:'.skills-container',item:'.item > div',cta:'a.cta',event:'Skills'},{container:'.statistics-container',item:'.item > a',cta:'a.cta',event:'Chiffres'},{container:'.popular-container .popular-term',item:'.item > a',cta:'a.cta',event:'Tags populaires'},];function add_click_event(value){container_count=$(value.container).length;if(container_count){let showcount=!1;if(container_count>1){showcount=!0}
$(value.container).each(function(container_index){event_libelle='Homepage - '+value.event
if(showcount){event_libelle=event_libelle+' (Liste '+(container_index+1)+')'}
$(this).find(value.item).each(function(item_index){$(this).attr('event',btoa(event_libelle+' - '+(item_index+1))).addClass('hp-events')});if(value.cta!=''){$(this).find(value.cta).attr('event',btoa(event_libelle+' - CTA')).addClass('hp-events')}})}}
$.each(tracked_area,function(key,value){add_click_event(value)});$(document).on('click','.hp-events',function(e){if($(this).val('event')){dataLayer.push({'event':'EventGeneric','EventCat':'Encart','EventAction':'Redirection','EventLibelle':atob($(this).attr('event'))})}})})})(jQuery)